Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
	Global.Microsoft.VisualBasic.HideModuleNameAttribute()>
	Friend Module Resources

		Private resourceMan As Global.System.Resources.ResourceManager

		Private resourceCulture As Global.System.Globalization.CultureInfo

'		internal Resources()
'		{
'		}

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _default() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("default", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property add_16x16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("add_16x16", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property addfile_16x16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("addfile_16x16", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property additem_16x16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("additem_16x16", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property apply_16x16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("apply_16x16", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property art_artistic_blur_1019341() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("art-artistic-blur-1019341", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property at_sign_rotating() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("at_sign_rotating", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property bright_color_colored_markers_1152665() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("bright-color-colored-markers-1152665", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property convert_16x16() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("convert_16x16", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property Dalmatian_runs() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Dalmatian_runs", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Byte[].
		''' </summary>
		Friend ReadOnly Property database() As Byte()
			Get
				Dim obj As Object = ResourceManager.GetObject("database", resourceCulture)
				Return (DirectCast(obj, Byte()))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to TestDescription.
		''' </summary>
		Friend ReadOnly Property Description() As String
			Get
				Return ResourceManager.GetString("Description", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
		''' </summary>
		Friend ReadOnly Property isBlackFridayDiscount() As DevExpress.Utils.Svg.SvgImage
			Get
				Dim obj As Object = ResourceManager.GetObject("isBlackFridayDiscount", resourceCulture)
				Return (DirectCast(obj, DevExpress.Utils.Svg.SvgImage))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to NameForTest.
		''' </summary>
		Friend ReadOnly Property Name() As String
			Get
				Return ResourceManager.GetString("Name", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property newImage() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("newImage", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Short.
		''' </summary>
		Friend ReadOnly Property ShortName() As String
			Get
				Return ResourceManager.GetString("ShortName", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property Untitled() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Untitled", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property
	End Module
End Namespace
